### ISSUE TITLE
[FEATURE]: Optionally add sklearn's `TimeSeriesSplit`

### ISSUE THREAD

**Issue by kspieks** [JacksonBurns/astartes#166]
Our current time-based splitter only returns one split of the data. If users want multiple time-based splits, they would need to make multiple calls. We could definitely write a short function that wrap ours, but I'll just also share this as another option. It would require the data to already be sorted by time
https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.TimeSeriesSplit.html

**Comment by JacksonBurns** [comment]
@kspieks this would be a cool one to have - this would ignore the requested split sizes, right?

**Comment by JacksonBurns** [comment]
Following up on this after some time - now that `astartes` is used in a few different places, we see that it is easier to require the end users to make repeat calls rather than for us to implement it here. Going to go ahead and close this, but leave it as not completed since this may change in the future.
