### ISSUE TITLE
[QUESTION]: Way to get the inputs back out from train_test_split_molecules?

### ISSUE THREAD

**Issue by ericchen384** [JacksonBurns/astartes#91]
**What are you trying to do?**

using train_test_split_molecules, I want to get back both indices and Morgan fingerprint

I put in my list of SMILES strings, which then get converted into molecule descriptors, and split, and get back out X_train and X_test, giving back two arrays of Morgan fingerprints.

Is there a tag I'm missing for which I can get the SMILES strings back? 

**Previous attempts**

I put in my list of SMILES strings, which then get converted into molecule descriptors, and split, and get back out X_train and X_test, giving back two arrays of Morgan fingerprints. I can use the return_indices = True to get the indices, but then I lose the Morgan Fingerprint conversion. 

Is there a tag I'm missing for which I can get both?

**Comment by kspieks** [comment]
Thanks for your question. The behavior is expected in the current implementation since the `return_indices` flag will override the output so it only returns indices rather than indices and original X input (SMILES strings in this case). [Code snippet](https://github.com/JacksonBurns/astartes/blob/main/astartes/main.py#L222-L226)
```
if return_indices:
        if val_idxs.any():
            return train_idxs, val_idxs, test_idxs
        else:
            return train_idxs, test_idxs
```

So it appears there is currently no option to get both outputs in one run. I'll discuss with @JacksonBurns this week about how/if we want to redesign this.

**Comment by kspieks** [comment]
Closing for now but feel free to open a new issue with any other questions :)
